### PR TITLE
Add skip_validation decorator to bypass CSRF validation programatically

### PR DESCRIPTION
**Pull request by bjudson**
This allows controlling validation() calls without applying @exempt decorator to each endpoint. Useful when performing widespread manual validation (eg through a custom view decorator or before_request hook).

Happy to add documentation if this makes sense to merge.

### CODE REVIEW

**Comment by bjudson** [comment]
Those test failures confuse me, but they look the same/similar to the ones failing on `master`. FWIW all tests pass on my laptop running Python 3.6.

**Comment by bjudson** [comment]
Is anyone maintaining this project?

**Comment by maxcountryman** [comment]
Closing as tests aren’t passing.

**Comment by bjudson** [comment]
It appears that tests are failing on master.

https://travis-ci.org/maxcountryman/flask-seasurf/builds/432163366

**Pull request closed without merging**
